##########################################################
#   Dockerfile (RestAPI)
#   
#   Este es un archivo desarrollado para la empresa
#   RT4 y su uso y distribución esta limitada a las 
#   condiciones propuestas por la empresa.
#
#   Copryrigth: 2024-2025
##########################################################
FROM python:3.12-slim

### Varnames
ARG WORKPATH=/opt/FastAPI/src


### Copy files
WORKDIR ${WORKPATH}
COPY requirements.txt ./
COPY . ./

### Create a user and set the environment variables
RUN useradd -m FastUser
USER FastUser
ENV PATH=/home/FastUser/.local/bin:$PATH
ENV PYTHONUSERBASE=/home/FastUser/.local


### Pipeline
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000

#CMD [ "fastapi", "dev", "app.py" ]
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
